"use client";
import "./globals.css";
import { SidebarDemo } from "@/components/Navbar";
import { useEffect, useState } from "react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="flex bg-[#1B1B1B] text-[#ddffdc] mx-20">
          {children}
      </body>
    </html>
  );
}
